image: python:3.7.3
pipelines:
  default:
    - step:
        caches:
          - node
        script: 
          - pip install -r src/requirements.txt
          
  branches:
    deploy/nightly: 
                - step: 
                    caches:
                      - node
                    script: 
                      - yarn
                      - yarn test:ci
                - step:
                    name: Deploying to dev
                    deployment: test
                    trigger: automatic
                    script:
                      
                      - curl http://www.nu.nl